### ISSUE TITLE
Need proper handling for RDMA_CM_EVENT_ROUTE_ERROR

### ISSUE THREAD

**Issue by lynus** [zrlio/disni#41]
I encountered in a situation where client randomly receive RDMA_CM_EVENT_ROUTE_ERROR, when client connects the server at a relately high frequence.  Disni does not handle this case properly, as it would block indefinitely in RdmaEndpoint.connect(). 
I think an automatic retry or throwing an exception would be enough to handle this kind of CM situations.

**Comment by lynus** [comment]
Actually this is not a big problem. RdmaEndpoint.dispatchCmEvent() just needs to notifyAll() in handling unknown CM event.

**Comment by lynus** [comment]
@patrickstuedi Yes，I have confirmed that. This is due to RdmaEndpoint.dispatchCmEvent does not notifyAll() when receiving unknow events.

**Comment by patrickstuedi** [comment]
Did you check if pulling notifyAll() out of the "if" statements helps?

https://github.com/zrlio/disni/blob/master/src/main/java/com/ibm/disni/RdmaEndpoint.java#L135

**Comment by patrickstuedi** [comment]
Ok, understand. But can we not solve this issue even simpler:

1) Make close() robust with regard to partially initialized state. For instance, by checking if RdmaCmId is open before calling getVerbs() in the close() call

https://github.com/zrlio/disni/blob/cfcee63cf054fb151f459357f601d7717f658b6c/src/main/java/com/ibm/disni/RdmaActiveEndpointGroup.java#L113

2) By rewriting the connect() call so that it remembers its state and starts from there, e.g., not binding if it is already bound, etc.

**Comment by lynus** [comment]
> Make close() robust with regard to partially initialized state. For instance, by checking if RdmaCmId is open before calling getVerbs() in the close() call
This only makes RdmaEndpoint itself robust, not the derived class. I still think isResourceAllocated() is needed, to inform derived class whether init() has been successfully executed. For example, the close() of DaRPCEndpoint should be:
`super.close();`
`if (isResourceAllocated())`
  `  derigisterMemory(dataMr);`

**Comment by lynus** [comment]
@PepperJo We can't simply set connState to CONN_STATE_INITIALIZED and then connect() again, because 
idPriv.resolveAddr() would fail since ep may have already bond to a device. 
My PR introduces a separate state isError to mark the prior error. connect() method then try to avoid unnecessary steps.
